version: "3"

services:
  front-app:
    build:
      context: front-app
    volumes:
      - ./front-app:/projects
    ports:
      - "4200:4200"
      - "6006:6006"
    entrypoint: ng serve --host 0.0.0.0 --disable-host-check
